#############################################################################
# Makefile for building: AfricaDemo
# Generated by qmake (2.01a) (Qt 4.5.3) on: Thu Nov 8 10:40:14 2018
# Project:  AfricaDemo.pro
# Template: app
# Command: /opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/qmake -spec /opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/linux-g++ -unix -o Makefile AfricaDemo.pro
#############################################################################

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe $(OE_QMAKE_CFLAGS) -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe $(OE_QMAKE_CFLAGS) $(OE_QMAKE_CXXFLAGS) -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/linux-g++ -I. -I/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/include/QtCore -I/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/include/QtGui -I/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/include -Isrc -I.
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS) -Wl,-rpath-link,/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/lib
LIBS          = $(SUBLIBS)  -L/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/lib -L/home/jiawei-james/deuta_workdir/projects/NFSoftware/AfricaDemo0918/src/ -lenvcon -lQtGui -L/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/lib -lfreetype -lXrender -L/opt/deuta-mft-i586-2.6/oetmp/staging/i586-linux/lib -lfontconfig $(OE_QMAKE_LIBS_X11) -lQtCore -lm -lrt -ldl -lpthread
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
QMAKE         = /opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		Core/CXAbstractWidget.cpp \
		pagealltop.cpp \
		tcmscomm/cl1_1.c \
		tcmscomm/host_dep.c \
		tcmscomm/tcmscontroller.cpp \
		tcmscomm/tcmsport.cpp \
		tcmscomm/tcmsAfricaTimebuffer.cpp \
		tcmscomm/tcmsAfricabuffer.cpp \
		pagegeneral.cpp \
		components/scalepawidget.cpp \
		components/analogclockwidget.cpp \
		components/scaleaccwidget.cpp \
		components/notchbarwidget.cpp \
		components/scalebarwidget.cpp \
		components/scaleunitwidget.cpp \
		components/scalecontentwidget.cpp \
		Logic/logic_page_alltop.cpp \
		tcmscomm/tcmsHMIAfricabuffer.cpp moc_mainwindow.cpp \
		moc_CXAbstractWidget.cpp \
		moc_pagealltop.cpp \
		moc_tcmscontroller.cpp \
		moc_tcmsport.cpp \
		moc_tcmsAfricaTimebuffer.cpp \
		moc_tcmsAfricabuffer.cpp \
		moc_pagegeneral.cpp \
		moc_scalepawidget.cpp \
		moc_analogclockwidget.cpp \
		moc_scaleaccwidget.cpp \
		moc_notchbarwidget.cpp \
		moc_scalebarwidget.cpp \
		moc_scaleunitwidget.cpp \
		moc_scalecontentwidget.cpp \
		moc_logic_page_alltop.cpp \
		moc_tcmsHMIAfricabuffer.cpp
OBJECTS       = main.o \
		mainwindow.o \
		CXAbstractWidget.o \
		pagealltop.o \
		cl1_1.o \
		host_dep.o \
		tcmscontroller.o \
		tcmsport.o \
		tcmsAfricaTimebuffer.o \
		tcmsAfricabuffer.o \
		pagegeneral.o \
		scalepawidget.o \
		analogclockwidget.o \
		scaleaccwidget.o \
		notchbarwidget.o \
		scalebarwidget.o \
		scaleunitwidget.o \
		scalecontentwidget.o \
		logic_page_alltop.o \
		tcmsHMIAfricabuffer.o \
		moc_mainwindow.o \
		moc_CXAbstractWidget.o \
		moc_pagealltop.o \
		moc_tcmscontroller.o \
		moc_tcmsport.o \
		moc_tcmsAfricaTimebuffer.o \
		moc_tcmsAfricabuffer.o \
		moc_pagegeneral.o \
		moc_scalepawidget.o \
		moc_analogclockwidget.o \
		moc_scaleaccwidget.o \
		moc_notchbarwidget.o \
		moc_scalebarwidget.o \
		moc_scaleunitwidget.o \
		moc_scalecontentwidget.o \
		moc_logic_page_alltop.o \
		moc_tcmsHMIAfricabuffer.o
DIST          = /opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/qconfig.pri \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/qt_functions.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/qt_config.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/exclusive_builds.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/default_pre.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/release.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/default_post.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/warn_on.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/qt.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/unix/thread.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/moc.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/resources.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/uic.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/yacc.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/lex.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/include_source_dir.prf \
		AfricaDemo.pro
QMAKE_TARGET  = AfricaDemo
DESTDIR       = 
TARGET        = AfricaDemo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /home/jiawei-james/deuta_workdir/projects/NFSoftware/AfricaDemo0918/src/libenvcon.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AfricaDemo.pro  /opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/linux-g++/qmake.conf /opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/qconfig.pri \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/qt_functions.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/qt_config.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/exclusive_builds.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/default_pre.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/release.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/default_post.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/warn_on.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/qt.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/unix/thread.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/moc.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/resources.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/uic.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/yacc.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/lex.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/include_source_dir.prf \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/lib/libQtGui.prl \
		/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/lib/libQtCore.prl
	$(QMAKE) -spec /opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/linux-g++ -unix -o Makefile AfricaDemo.pro
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/qconfig.pri:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/qt_functions.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/qt_config.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/exclusive_builds.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/default_pre.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/release.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/default_post.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/warn_on.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/qt.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/unix/thread.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/moc.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/resources.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/uic.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/yacc.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/lex.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/features/include_source_dir.prf:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/lib/libQtGui.prl:
/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/mkspecs/linux-g++ -unix -o Makefile AfricaDemo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/AfricaDemo1.0.0 || $(MKDIR) .tmp/AfricaDemo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/AfricaDemo1.0.0/ && $(COPY_FILE) --parents mainwindow.h Core/CXAbstractWidget.h pagealltop.h tcmscomm/cl1_1.h tcmscomm/cl1_ret.h tcmscomm/config.h tcmscomm/dpr_dep.h tcmscomm/host_dep.h tcmscomm/mvb.h src/disphw32.h src/windefs.h tcmscomm/tcmscontroller.h tcmscomm/tcmsport.h tcmscomm/tcmsAfricaTimebuffer.h tcmscomm/tcmsAfricabuffer.h pagegeneral.h components/scalepawidget.h components/analogclockwidget.h components/scaleaccwidget.h components/notchbarwidget.h components/scalebarwidget.h components/scaleunitwidget.h components/scalecontentwidget.h Logic/logic_page_alltop.h tcmscomm/tcmsHMIAfricabuffer.h .tmp/AfricaDemo1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp Core/CXAbstractWidget.cpp pagealltop.cpp tcmscomm/cl1_1.c tcmscomm/host_dep.c tcmscomm/tcmscontroller.cpp tcmscomm/tcmsport.cpp tcmscomm/tcmsAfricaTimebuffer.cpp tcmscomm/tcmsAfricabuffer.cpp pagegeneral.cpp components/scalepawidget.cpp components/analogclockwidget.cpp components/scaleaccwidget.cpp components/notchbarwidget.cpp components/scalebarwidget.cpp components/scaleunitwidget.cpp components/scalecontentwidget.cpp Logic/logic_page_alltop.cpp tcmscomm/tcmsHMIAfricabuffer.cpp .tmp/AfricaDemo1.0.0/ && (cd `dirname .tmp/AfricaDemo1.0.0` && $(TAR) AfricaDemo1.0.0.tar AfricaDemo1.0.0 && $(COMPRESS) AfricaDemo1.0.0.tar) && $(MOVE) `dirname .tmp/AfricaDemo1.0.0`/AfricaDemo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/AfricaDemo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_CXAbstractWidget.cpp moc_pagealltop.cpp moc_tcmscontroller.cpp moc_tcmsport.cpp moc_tcmsAfricaTimebuffer.cpp moc_tcmsAfricabuffer.cpp moc_pagegeneral.cpp moc_scalepawidget.cpp moc_analogclockwidget.cpp moc_scaleaccwidget.cpp moc_notchbarwidget.cpp moc_scalebarwidget.cpp moc_scaleunitwidget.cpp moc_scalecontentwidget.cpp moc_logic_page_alltop.cpp moc_tcmsHMIAfricabuffer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_CXAbstractWidget.cpp moc_pagealltop.cpp moc_tcmscontroller.cpp moc_tcmsport.cpp moc_tcmsAfricaTimebuffer.cpp moc_tcmsAfricabuffer.cpp moc_pagegeneral.cpp moc_scalepawidget.cpp moc_analogclockwidget.cpp moc_scaleaccwidget.cpp moc_notchbarwidget.cpp moc_scalebarwidget.cpp moc_scaleunitwidget.cpp moc_scalecontentwidget.cpp moc_logic_page_alltop.cpp moc_tcmsHMIAfricabuffer.cpp
moc_mainwindow.cpp: mainwindow.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_CXAbstractWidget.cpp: Core/CXAbstractWidget.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) Core/CXAbstractWidget.h -o moc_CXAbstractWidget.cpp

moc_pagealltop.cpp: Core/CXAbstractWidget.h \
		Logic/logic_page_alltop.h \
		tcmscomm/tcmsAfricabuffer.h \
		tcmscomm/tcmsAfricaTimebuffer.h \
		pagealltop.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) pagealltop.h -o moc_pagealltop.cpp

moc_tcmscontroller.cpp: tcmscomm/tcmscontroller.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) tcmscomm/tcmscontroller.h -o moc_tcmscontroller.cpp

moc_tcmsport.cpp: tcmscomm/tcmsport.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) tcmscomm/tcmsport.h -o moc_tcmsport.cpp

moc_tcmsAfricaTimebuffer.cpp: tcmscomm/tcmsAfricaTimebuffer.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) tcmscomm/tcmsAfricaTimebuffer.h -o moc_tcmsAfricaTimebuffer.cpp

moc_tcmsAfricabuffer.cpp: tcmscomm/tcmsAfricabuffer.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) tcmscomm/tcmsAfricabuffer.h -o moc_tcmsAfricabuffer.cpp

moc_pagegeneral.cpp: Core/CXAbstractWidget.h \
		pagegeneral.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) pagegeneral.h -o moc_pagegeneral.cpp

moc_scalepawidget.cpp: Core/CXAbstractWidget.h \
		components/scalepawidget.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) components/scalepawidget.h -o moc_scalepawidget.cpp

moc_analogclockwidget.cpp: Core/CXAbstractWidget.h \
		components/analogclockwidget.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) components/analogclockwidget.h -o moc_analogclockwidget.cpp

moc_scaleaccwidget.cpp: Core/CXAbstractWidget.h \
		components/scaleaccwidget.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) components/scaleaccwidget.h -o moc_scaleaccwidget.cpp

moc_notchbarwidget.cpp: Core/CXAbstractWidget.h \
		components/notchbarwidget.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) components/notchbarwidget.h -o moc_notchbarwidget.cpp

moc_scalebarwidget.cpp: Core/CXAbstractWidget.h \
		components/scalebarwidget.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) components/scalebarwidget.h -o moc_scalebarwidget.cpp

moc_scaleunitwidget.cpp: Core/CXAbstractWidget.h \
		components/scaleunitwidget.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) components/scaleunitwidget.h -o moc_scaleunitwidget.cpp

moc_scalecontentwidget.cpp: Core/CXAbstractWidget.h \
		tcmscomm/tcmsAfricabuffer.h \
		components/scalecontentwidget.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) components/scalecontentwidget.h -o moc_scalecontentwidget.cpp

moc_logic_page_alltop.cpp: tcmscomm/tcmsAfricabuffer.h \
		tcmscomm/tcmsAfricaTimebuffer.h \
		Logic/logic_page_alltop.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) Logic/logic_page_alltop.h -o moc_logic_page_alltop.cpp

moc_tcmsHMIAfricabuffer.cpp: tcmscomm/tcmsHMIAfricabuffer.h
	/opt/MFT_SDK/Qt-4.5.3-sdk-mft-i586-2.6/bin/moc $(DEFINES) $(INCPATH) tcmscomm/tcmsHMIAfricabuffer.h -o moc_tcmsHMIAfricabuffer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		pagealltop.h \
		Core/CXAbstractWidget.h \
		Logic/logic_page_alltop.h \
		tcmscomm/tcmsAfricabuffer.h \
		tcmscomm/tcmsAfricaTimebuffer.h \
		pagegeneral.h \
		src/disphw32.h \
		src/windefs.h \
		tcmscomm/tcmscontroller.h \
		tcmscomm/tcmsHMIAfricabuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

CXAbstractWidget.o: Core/CXAbstractWidget.cpp Core/CXAbstractWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CXAbstractWidget.o Core/CXAbstractWidget.cpp

pagealltop.o: pagealltop.cpp pagealltop.h \
		Core/CXAbstractWidget.h \
		Logic/logic_page_alltop.h \
		tcmscomm/tcmsAfricabuffer.h \
		tcmscomm/tcmsAfricaTimebuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pagealltop.o pagealltop.cpp

cl1_1.o: tcmscomm/cl1_1.c tcmscomm/config.h \
		tcmscomm/host_dep.h \
		tcmscomm/dpr_dep.h \
		tcmscomm/cl1_ret.h \
		tcmscomm/cl1_1.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cl1_1.o tcmscomm/cl1_1.c

host_dep.o: tcmscomm/host_dep.c tcmscomm/config.h \
		tcmscomm/host_dep.h \
		tcmscomm/dpr_dep.h \
		tcmscomm/cl1_ret.h \
		tcmscomm/cl1_1.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o host_dep.o tcmscomm/host_dep.c

tcmscontroller.o: tcmscomm/tcmscontroller.cpp tcmscomm/mvb.h \
		tcmscomm/config.h \
		tcmscomm/host_dep.h \
		tcmscomm/dpr_dep.h \
		tcmscomm/cl1_ret.h \
		tcmscomm/cl1_1.h \
		tcmscomm/tcmscontroller.h \
		tcmscomm/tcmsport.h \
		tcmscomm/tcmsAfricabuffer.h \
		tcmscomm/tcmsHMIAfricabuffer.h \
		tcmscomm/tcmsAfricaTimebuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcmscontroller.o tcmscomm/tcmscontroller.cpp

tcmsport.o: tcmscomm/tcmsport.cpp tcmscomm/tcmsport.h \
		tcmscomm/mvb.h \
		tcmscomm/config.h \
		tcmscomm/host_dep.h \
		tcmscomm/dpr_dep.h \
		tcmscomm/cl1_ret.h \
		tcmscomm/cl1_1.h \
		tcmscomm/tcmscontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcmsport.o tcmscomm/tcmsport.cpp

tcmsAfricaTimebuffer.o: tcmscomm/tcmsAfricaTimebuffer.cpp tcmscomm/tcmsAfricaTimebuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcmsAfricaTimebuffer.o tcmscomm/tcmsAfricaTimebuffer.cpp

tcmsAfricabuffer.o: tcmscomm/tcmsAfricabuffer.cpp tcmscomm/tcmsAfricabuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcmsAfricabuffer.o tcmscomm/tcmsAfricabuffer.cpp

pagegeneral.o: pagegeneral.cpp pagegeneral.h \
		Core/CXAbstractWidget.h \
		components/scalebarwidget.h \
		components/scalepawidget.h \
		components/notchbarwidget.h \
		components/scaleaccwidget.h \
		tcmscomm/tcmsAfricabuffer.h \
		components/scaleunitwidget.h \
		components/analogclockwidget.h \
		components/scalecontentwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pagegeneral.o pagegeneral.cpp

scalepawidget.o: components/scalepawidget.cpp components/scalepawidget.h \
		Core/CXAbstractWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scalepawidget.o components/scalepawidget.cpp

analogclockwidget.o: components/analogclockwidget.cpp components/analogclockwidget.h \
		Core/CXAbstractWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analogclockwidget.o components/analogclockwidget.cpp

scaleaccwidget.o: components/scaleaccwidget.cpp components/scaleaccwidget.h \
		Core/CXAbstractWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scaleaccwidget.o components/scaleaccwidget.cpp

notchbarwidget.o: components/notchbarwidget.cpp components/notchbarwidget.h \
		Core/CXAbstractWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notchbarwidget.o components/notchbarwidget.cpp

scalebarwidget.o: components/scalebarwidget.cpp components/scalebarwidget.h \
		Core/CXAbstractWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scalebarwidget.o components/scalebarwidget.cpp

scaleunitwidget.o: components/scaleunitwidget.cpp components/scaleunitwidget.h \
		Core/CXAbstractWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scaleunitwidget.o components/scaleunitwidget.cpp

scalecontentwidget.o: components/scalecontentwidget.cpp components/scalecontentwidget.h \
		Core/CXAbstractWidget.h \
		tcmscomm/tcmsAfricabuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scalecontentwidget.o components/scalecontentwidget.cpp

logic_page_alltop.o: Logic/logic_page_alltop.cpp Logic/logic_page_alltop.h \
		tcmscomm/tcmsAfricabuffer.h \
		tcmscomm/tcmsAfricaTimebuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logic_page_alltop.o Logic/logic_page_alltop.cpp

tcmsHMIAfricabuffer.o: tcmscomm/tcmsHMIAfricabuffer.cpp tcmscomm/tcmsHMIAfricabuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcmsHMIAfricabuffer.o tcmscomm/tcmsHMIAfricabuffer.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_CXAbstractWidget.o: moc_CXAbstractWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CXAbstractWidget.o moc_CXAbstractWidget.cpp

moc_pagealltop.o: moc_pagealltop.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pagealltop.o moc_pagealltop.cpp

moc_tcmscontroller.o: moc_tcmscontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcmscontroller.o moc_tcmscontroller.cpp

moc_tcmsport.o: moc_tcmsport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcmsport.o moc_tcmsport.cpp

moc_tcmsAfricaTimebuffer.o: moc_tcmsAfricaTimebuffer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcmsAfricaTimebuffer.o moc_tcmsAfricaTimebuffer.cpp

moc_tcmsAfricabuffer.o: moc_tcmsAfricabuffer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcmsAfricabuffer.o moc_tcmsAfricabuffer.cpp

moc_pagegeneral.o: moc_pagegeneral.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pagegeneral.o moc_pagegeneral.cpp

moc_scalepawidget.o: moc_scalepawidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scalepawidget.o moc_scalepawidget.cpp

moc_analogclockwidget.o: moc_analogclockwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_analogclockwidget.o moc_analogclockwidget.cpp

moc_scaleaccwidget.o: moc_scaleaccwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scaleaccwidget.o moc_scaleaccwidget.cpp

moc_notchbarwidget.o: moc_notchbarwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_notchbarwidget.o moc_notchbarwidget.cpp

moc_scalebarwidget.o: moc_scalebarwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scalebarwidget.o moc_scalebarwidget.cpp

moc_scaleunitwidget.o: moc_scaleunitwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scaleunitwidget.o moc_scaleunitwidget.cpp

moc_scalecontentwidget.o: moc_scalecontentwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scalecontentwidget.o moc_scalecontentwidget.cpp

moc_logic_page_alltop.o: moc_logic_page_alltop.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logic_page_alltop.o moc_logic_page_alltop.cpp

moc_tcmsHMIAfricabuffer.o: moc_tcmsHMIAfricabuffer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcmsHMIAfricabuffer.o moc_tcmsHMIAfricabuffer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

